### ISSUE TITLE
Suggestion - let us move the chat to the edges of the screen

### ISSUE THREAD

**Issue by Daeveren** [ETSeki/prat-3-0#5]
Currently, the chat window is smaller than the Edit Mode panel, so when the user tries to move the Prat chat window to the edge of the screen, there's a significant empty space left there.
If the user has Leatrix Plus and checks the "unclamp chat frame" over there, then moving the Prat chat window with Edit Mode finally allows the chat to be moved right to the edge of the screen.
A similar feature should be added in Prat.

**Comment by ETSeki** [comment]
I changed the Zero Clamp Size option so it allows to move ChatFrame1 outside the screen. So now the real Chat window can be moved flush with the screen again. I will make a new release soon wich will also probably be the last one on this fork because the Legacy of Sylvanar fork is active and pushes updates to curseforge again so i will commit my changes there.

**Comment by Daeveren** [comment]
Awesome, thanks!
