### ISSUE TITLE
Please restore chat resize options - unrelated to Edit Mode

### ISSUE THREAD

**Issue by Voxxel** [ETSeki/prat-3-0#7]
It would be great if we could size and position the chat freely as before. WoW's new Edit Mode does not support to elevate the input field to top and when I do this with Prat there will be a gap in the bottom so can't manage it within Edit Mode. 

Is that possible to restore Prat's resize chat corner icons while Edit Mode is off?

**Comment by ETSeki** [comment]
I will take a look into it but this will most likely be more complex then the simple bug fixing i did until know so it will take some time. Until the Latrix Plus allows you to move the frame outside the window with the edit mode so there is no empty space at the bottom anymore. Maybe i can implement this function into prat.

**Comment by Voxxel** [comment]
Cool, thank you! <3

Would you mind to put your Prat version to CurseForge so we can follow and download updates through the updater apps without visiting Github everytime? Would be great!

**Comment by ETSeki** [comment]
I will try to make it compatible with the github update of wowup. Im not planning to release on Curseforge right now because i only wanted to fix the addon for the new addon and not support it long term because im not sure if i would be abble to implement new functions etc. I hope that i can my and others fixes get implemented in the Legacy of Sylvanar fork and they update the original on curseforge.

**Comment by ETSeki** [comment]
I changed the Zero Clamp Size option so it allows to move ChatFrame1 outside the screen. So now the real Chat window can be moved flush with the screen again. I will make a new release soon wich will also probably be the last one on this fork because the Legacy of Sylvanar fork is active and pushes updates to curseforge again so i will commit my changes there.

**Comment by Voxxel** [comment]
Thank you for your work, m8!
